layout = BoxLayout(orientation='vertical')
weatherForcast_Detect = Button(text='Weather Forcast')
catchRecord = Button(text='Record your catch')
fishingLocations = Button(text='Fishing locatoins')
layout.add_widget(weatherForcast_Detect)
layout.add_widget(catchRecord)
layout.add_widget(fishingLocations)
<Widgetry>:
    txt_inpt: txt_inpt
    Button:
        id: f_but
    TextInput:
        id: txt_inpt
        text: f_but.state
        on_text: root.check_status(f_but)
