#:kivy 1.8.0
<rootWidget>:
	fishName: txt_input

	BoxLayout:
		id: weatherForecast
		orientation: 'horizontal'
		Button:
			text: 'Weather Forecast'

	BoxLayout:
		id: fishingLocations
		orientation: 'horizontal'
		Button:
			text: 'Fishing Locations'

	
	BoxLayout:
		orientation: 'horizontal'
		Label:
			text: 'Please enter the name of the fish'
			font_size: 12

    	TextInput:
        	id: txt_input

