<EmailInterface>:
    orientation: 'vertical'
    GridLayout:
        Label:
            text: 'Recipient:'
        TextInput:
            id: recipient
    GridLayout:
        Label:
            text: 'Subject:'
        TextInput:
            id: subject
    GridLayout:
        Label:
            text: 'Text:'
        TextInput:
            id: text
    GridLayout:
        Label:
            text: 'create chooser?'
        CheckBox:
            id: create_chooser
    IntentButton:
        email_recipient: recipient.text
        email_subject: subject.text
        email_text: text.text
        create_chooser: create_chooser.active
        text: 'Send email'
        size_hint_y: None
        height: sp(40)
        on_release: self.send_email()
